{%set name = "bidict" %}
{%set version = "0.13.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "c7f4131ed516662b45350c01d69e84e990ab084c502bdcf25a179c56f5342674" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://github.com/jab/{{ name }}/archive/v{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - bidict

about:
  home: https://bidict.readthedocs.io
  license: ISC License (ISCL)
  license_file: LICENSE
  summary: 'Efficient, Pythonic bidirectional map implementation and related functionality'
  dev_url: https://github.com/jab/bidict
  doc_url: https://bidict.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - jab
