{%set name = "bidict" %}
{%set version = "0.14.2" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "e3c972d1a5367b1c903d4825c0645f0e6de6b57d64b78cf1c86d0187905af4ab" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://github.com/jab/{{ name }}/archive/v{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pytest-runner

  run:
    - python

test:
  imports:
    - bidict

about:
  home: https://bidict.readthedocs.io
  license: MPL-2.0
  license_file: LICENSE
  summary: 'Efficient, Pythonic bidirectional map implementation and related functionality'
  dev_url: https://github.com/jab/bidict
  doc_url: https://bidict.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - jab
