{% set name = "bidict" %}
{% set version = "0.20.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "c1b1ce1c0f1e3457489672bc3a4db375a06f61ae7797a9eedf71ea788cea3870" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.5
    - setuptools

test:
  imports:
    - bidict

about:
  home: https://bidict.readthedocs.io
  license: MPL-2.0
  license_file: LICENSE
  summary: Efficient, Pythonic bidirectional map implementation and related functionality
  dev_url: https://github.com/jab/bidict
  doc_url: https://bidict.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - jab
