{% set name = "bidict" %}
{% set version = "0.17.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f7c78846fda6e1fa9e20cd39beda53c6b2c16ae857c4e03918640cc8df21fbca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - pytest-runner

  run:
    - python
    - setuptools

test:
  imports:
    - bidict

about:
  home: https://bidict.readthedocs.io
  license: MPL-2.0
  license_file: LICENSE
  summary: 'Efficient, Pythonic bidirectional map implementation and related functionality'
  dev_url: https://github.com/jab/bidict
  doc_url: https://bidict.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - jab
