{% set name = "bidict" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0faeba6d5d5276d5b59ce71809b2f16d18a3d66b07791007714e09d60e8ad8ad

build:
  skip: true  # [py<311]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=40.9.0
    - wheel
    - uv_build >=0.8.13,<0.12
  run:
    - python
    - typing_extensions >=4.0  # [py<312]

test:
  imports:
    - bidict
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - hypothesis
    - typing_extensions
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m pytest -v tests

about:
  home: https://bidict.readthedocs.io
  license: MPL-2.0
  license_file: LICENSE
  license_family: MOZILLA
  summary: The bidirectional mapping library for Python.
  description: |
    The bidict library provides several friendly, efficient data structures for working with bidirectional mappings in Python.
  dev_url: https://github.com/jab/bidict
  doc_url: https://bidict.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - jab
