{% set name = "bidict" %}
{% set version = "0.18.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "4d10630fd5d86b7c165387473c5180e7fca7635f12e24b1f426aac259c72c81a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python
    - setuptools

test:
  imports:
    - bidict

about:
  home: https://bidict.readthedocs.io
  license: MPL-2.0
  license_file: LICENSE
  summary: 'Efficient, Pythonic bidirectional map implementation and related functionality'
  dev_url: https://github.com/jab/bidict
  doc_url: https://bidict.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - jab
