travis:
  secure:
    BINSTAR_TOKEN: cwzO48DKvlRUpD7v45/8Xv8LbF0vsSjGJbZsYwfR249KFQ9rFbD4C2eBFIRwIijXWcZyP1WqATmM+80AkZEXMfVa7x00oA6q9U5wFqwOJTWn7yZ1DisYzl+liLargiRgg4rKxbW+8HylOV76yvNmLPGQHsVtCCmBjCC1w2oqFSOf2ckXtCTxa5Hgy7e28Y4gscm4a3Bfif5+KWASxRInT/h2LoG5+DMyJgUwJmxKn8TFIm8mamU+UTmjKveRijuRaY+pb7/23GYmItun0QSq1BpmIxmZNyCQhGb5NjjO4U88gwHQwNq3SWnxsbqmMlxzkF1EiIi9AU82QCn73bNb38YTBnTBWB89ZZZu0JdN/1V0ULXaraxRQy9ffSI9CJ133dusUnH6IlrT2webW7UF72zvtqxUQn2LyQT1u/v8QZKcF/hHEx7NYHuygBegrZpNYYXc7AH8MZ3Vk8ZrA0xs3e+c4od4zz08UspCT5ZzBYel8ajPWubZHx/IShbPU9/+ycVSKHSx//OU7vFdUp73958X+s65uuSBTyVcr9nfeNeYRPUsINX2YeE7e5WYO4oLbW2i6/P7e/BrjQpbtG5OaWDBS0v5zijgQ9HzjB266jihMWa+a4CDTBv1Xlo9DihO+FcrUKhGEBuNA6HoMRrJbBjKii/DA4MTc8cpkbLqnDA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
