travis:
  secure:
    BINSTAR_TOKEN: BiFnDwo+H0wLPJXxtwZOPFGHGadOw1jgxfuh2htiDfY+0zu1R18MEEGfUGHYrJJpttpnk3tfVur9tCdH4mOEr8wUYdZKdH++T3+bCtKw8PKsz2i/OZ5BBy9uq0aKdQjfVMF3DVQc/Ng0HkuHgnV+uiDj38VxlqqOtfMeXmJycdV5VhYo074Z2EbzAK5ivtUm+fY4H1DWkM0fvyS3m2Ug5TMXFJ6KW51iO3T7BEJmZBDflNBZqP4zQhC11iH8RKg+bNkgdWlIpTUN6ymvgXRay41IDb1w8lFdN00VSQTIgyKQTROuXQ2GpdwztvG/sdFG0PUvE2zUzN0MbRjgq3y99YaZRPMMeLDpiJya8UzGLLR+CuJcA7k6TD/baOEmMEULVGhZRFi9Znu9UEoWABAAEHmh6bwha3MSqAlxoFrJACiX+I1BJuo3NRjEP9ZXo9i6AzkzvBXC0OgcL4j613jzafVt0/YluNmZFESkQ+qbLP0sn2wVi3k5JWSyKmyNO7r6L3Q5J4j+GuBsASzc4Y8JaFB3oVvTQBMTdhCNsFJA18oD/OwsIz9etlIO/vrTiZVihZUtkt5cQo38wadjt5zyK82iInmHuTUHBbrkNXHAOEFLmZ9i3kNCIh/M42usGqh3zbW+jfPgJz/hywecl0x7C2q7+Zac9qxWrClQw6KLDiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
